---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-frontend-deployment
spec:
  selector:
    matchLabels:
      app: hello
      tier: app-frontend-deployment
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        tier: app-frontend-deployment
        track: stable
    spec:
      containers:
        - name: app-frontend
          image: localhost:32000/app-frontend
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
---
apiVersion: v1
kind: Service
metadata:
  name: app-frontend-service
  labels:
    app: hello
spec:
  selector:
    app: hello
    tier: app-frontend-deployment
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
  type: NodePort
