---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-backend-deployment
spec:
  selector:
    matchLabels:
      app: hello
      tier: app-backend-deployment
      track: stable
  replicas: 3
  template:
    metadata:
      labels:
        app: hello
        tier: app-backend-deployment
        track: stable
    spec:
      containers:
        - name: app-backend
          image: localhost:32000/app-backend
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app-backend-service
  labels:
    app: hello
spec:
  selector:
    app: hello
    tier: app-backend-deployment
  ports:
  - protocol: TCP
    name: http
    port: 5000
    targetPort: 5000
  type: NodePort
